seed: 2333
dataset:
  val_ratio: 0.2
  test_ratio: 0.2
  num_workers: 4
  persistent_workers: True
model:
  in_channels: 1
  out_channels: 1
  block_out_channels: [128, 256, 512, 512]
  down_block_types: ['DownEncoderBlock2D', 'DownEncoderBlock2D', 'DownEncoderBlock2D', 'DownEncoderBlock2D']
  up_block_types: ['UpDecoderBlock2D', 'UpDecoderBlock2D', 'UpDecoderBlock2D', 'UpDecoderBlock2D']
  layers_per_block: 2
  act_fu: "silu"
  latent_channels: 64
  norm_num_groups: 32
loss:
  disc_start: 10001
  kl_weight: 1e-6
  disc_weight: 0.5
  perceptual_weight: 0.1
  disc_in_channels: 1
optim:
  accelerator: "gpu"
  precision: "16-mixed"
  batch_size: 8
  float32_matmul_precision: "medium"
  method: "adam"
  lr: 1e-3
  betas: [0.5, 0.9]
  gradient_clip_val: 1.0
  max_epochs: 500
  # scheduler
  warmup_percentage: 0.1
  lr_scheduler_mode: "cosine"
  min_lr_ratio: 1.0e-3
  warmup_min_lr_ratio: 0.1
  # early stopping
  monitor: "val/total_loss"
  patience: 5
